import { Setting } from "../../lib/types";
import { Earth, Globe, Bell, Router, Wifi, RefreshCw, KeyRound, Database, DatabaseZap, Package, Tag, AudioWaveform, ALargeSmall, MapPin, HatGlasses, DatabaseBackup, ShieldAlert, Bird, Gpu, Tv, Videotape, BookHeadphones, Link, Blend, Gauge, Ear, Wrench, Activity, WifiSync, Diff, ScrollText, LocateFixed, BatteryCharging } from "lucide-react";

export const DEFAULT_SETTINGS: Setting[] = [
    {
        id: "connection",
        name: "Connection",
        description: "Shows your device's connection name",
        defaultValue: "MyBirdNETPiHotspot",
        tab: "SYNCING",
        type: "string",
        icon: <Wifi size={18} />,
        disabled: true,
        value: "MyBirdNETPiHotspot",
    },
    {
        id: "deleteSyncedData",
        name: "Delete synced data",
        description: "Delete your data from the device after successful sync",
        defaultValue: false,
        tab: "SYNCING",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
    },
    {
        id: "scenarioName",
        name: "Scenario Name",
        description: "Keep organized by assigning a scenario name to the benchmarking tests.",
        defaultValue: "App start",
        tab: "BENCHMARKING",
        type: "string",
        icon: <ALargeSmall size={18} />,
        value: "App start",
    },
    {
        id: "birdWeatherToken",
        name: "BirdWeather Token",
        description: "Token for BirdWeather to share your detections with the community platform",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <Bird size={18} />,
        value: "",
    },
    {
        id: "mapTilerApiKey",
        name: "MapTiler API Key",
        description: "API key for MapTiler to unlock improved map features",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <KeyRound size={18} />,
        value: "",
    },
    {
        id: "supabaseUrl",
        name: "Supabase URL",
        description: "URL for your Supabase instance to enable cloud syncing",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <Database size={18} />,
        value: "",
    },
    {
        id: "supabaseKey",
        name: "Supabase Key",
        description: "Publishable key for your Supabase instance",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <DatabaseZap size={18} />,
        value: "",
    },

    // Device internal settings
    // Basic settings
    {
        id: "MODEL",
        name: "Model",
        description: "Type of model used for predictions",
        defaultValue: "BirdNET_GLOBAL_6K_V2.4_Model_FP16",
        tab: "MODEL",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "BirdNET_GLOBAL_6K_V2.4_Model_FP16", value: "BirdNET_GLOBAL_6K_V2.4_Model_FP16" },
            { label: "BirdNET_6K_GLOBAL_MODEL", value: "BirdNET_6K_GLOBAL_MODEL" },
        ],
        icon: <Package size={18} />,
        value: "BirdNET_GLOBAL_6K_V2.4_Model_FP16",
        deviceInternal: true,
    },
    {
        id: "DATA_MODEL_VERSION",
        name: "Species range model V2.4 - V2",
        description: "Version of the species range model used for predictions",
        defaultValue: false,
        tab: "MODEL",
        topTab: "BASIC",
        type: "boolean",
        icon: <Tag size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "SF_THRESH",
        name: "Species Occurrence Frequency Threshold",
        description: "Minimum occurrence frequency for a species to be included in the model's output",
        defaultValue: 0.03,
        tab: "MODEL",
        topTab: "BASIC",
        type: "number",
        icon: <AudioWaveform size={18} />,
        value: 0.03,
        min: 0.0005,
        max: 0.99,
        deviceInternal: true,
    },
    {
        id: "SITE_NAME",
        name: "Site Name",
        description: "The name of your device",
        defaultValue: "birdnet",
        tab: "LOCATION",
        topTab: "BASIC",
        type: "string",
        icon: <ALargeSmall size={18} />,
        value: "birdnet",
        deviceInternal: true,
    },
    {
        id: "GPS_INTERVAL",
        name: "GPS Interval",
        description: "Interval for GPS updates in seconds",
        defaultValue: 900,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "number",
        icon: <LocateFixed size={18} />,
        value: 900,
        min: 60,
        max: 3600,
        deviceInternal: true,
    },
    {
        id: "GPS_POWER_SAVE_MODE",
        name: "GPS Power Save Mode",
        description: "Enable or disable GPS power save mode",
        defaultValue: true,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "boolean",
        icon: <BatteryCharging size={18} />,
        value: true,
        deviceInternal: true,
    },
    {
        id: "LATITUDE",
        name: "Latitude",
        description: "Latitude of the device location",
        defaultValue: 49.0181,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "number",
        icon: <MapPin size={18} />,
        value: 49.0181,
        min: -90.0,
        max: 90.0,
        step: 0.0001,
        deviceInternal: true,
        disabled: true
    },
    {
        id: "LONGITUDE",
        name: "Longitude",
        description: "Longitude of the device location",
        defaultValue: 12.1404,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "number",
        icon: <MapPin size={18} />,
        value: 12.1404,
        min: -180.0,
        max: 180.0,
        step: 0.0001,
        deviceInternal: true,
        disabled: true
    },
    {
        id: "BIRDWEATHER_ID",
        name: "BirdWeather Token",
        description: "Used for sharing your data with the BirdWeather community platform",
        defaultValue: "",
        tab: "BIRDWEATHER",
        topTab: "BASIC",
        type: "string",
        icon: <Router size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "APPRISE_INPUT",
        name: "Apprise Notifications Configuration",
        description: "More here: <a href='https://github.com/caronc/apprise/wiki'>Apprise Documentation</a>",
        defaultValue: "",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "textarea",
        icon: <Bell size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "APPRISE_NOTIFICATION_TITLE",
        name: "Apprise Notification Title",
        description: "Title for Apprise notifications",
        defaultValue: "New BirdNET-Pi Detection",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "string",
        icon: <Router size={18} />,
        value: "New BirdNET-Pi Detection",
        deviceInternal: true,
    },
    {
        id: "APPRISE_NOTIFICATION_BODY",
        name: "Apprise Notification Body",
        description: "Body for Apprise notifications",
        defaultValue: "A $comname ($sciname)  was just detected with a confidence of $confidence ($reason)",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "textarea",
        icon: <Bell size={18} />,
        value: "A $comname ($sciname)  was just detected with a confidence of $confidence ($reason)",
        deviceInternal: true,
    },
    {
        id: "APPRISE_NOTIFY_NEW_SPECIES",
        name: "Notify each new infrequent species detection",
        description: "<5 visits per week",
        defaultValue: false,
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY",
        name: "Notify each species first detection of the day",
        description: "Only the first time a species is detected each day",
        defaultValue: false,
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "APPRISE_NOTIFY_EACH_DETECTION",
        name: "Notify each new detection",
        description: "Notify for each detection",
        defaultValue: false,
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "APPRISE_WEEKLY_REPORT",
        name: "Send weekly report",
        description: "Receive a weekly report of detections",
        defaultValue: false,
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES",
        name: "Minimum time between notifications of the same species (sec)",
        description: "Minimum time in seconds between notifications for the same species",
        defaultValue: 0,
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "number",
        icon: <Router size={18} />,
        value: 0,
        deviceInternal: true,
    },
    {
        id: "APPRISE_ONLY_NOTIFY_SPECIES_NAMES",
        name: "Exclude these species",
        description: "Comma separated common names",
        defaultValue: "",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "string",
        icon: <Router size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "APPRISE_ONLY_NOTIFY_SPECIES_NAMES_2",
        name: "ONLY notify for these species",
        description: "Comma separated common names",
        defaultValue: "",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "string",
        icon: <Router size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "DATABASE_LANG",
        name: "Database Language",
        description: "! Only modify this at initial setup !",
        defaultValue: "en",
        tab: "LOCALIZATION",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "Afrikaans", value: "af" },
            { label: "Arabic", value: "ar" },
            { label: "Catalan", value: "ca" },
            { label: "Czech", value: "cs" },
            { label: "Chinese (simplified)", value: "zh_CN" },
            { label: "Chinese (traditional)", value: "zh_TW" },
            { label: "Croatian", value: "hr" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Indonesia", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuania", value: "lt" },
            { label: "Norwegian", value: "no" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Serbian", value: "sr" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Thai", value: "th" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" },
            { label: "Vietnamese", value: "vi" },
        ],
        icon: <Globe size={18} />,
        value: "en",
        deviceInternal: true,
        disabled: true
    },
    {
        id: "retrieveTimeAutomatically",
        name: "Retrieve Time",
        description: "Automatically retrieve the current time from the network",
        defaultValue: true,
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: true,
        deviceInternal: true,
        disabled: true
    },
    {
        id: "TIMEZONE",
        name: "Select a Timezone",
        description: "Select the timezone for your device to ensure correct timestamping of detections",
        defaultValue: "Europe/Berlin",
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "Africa/Abidjan", value: "Africa/Abidjan" },
            { label: "Africa/Accra", value: "Africa/Accra" },
            { label: "Africa/Addis_Ababa", value: "Africa/Addis_Ababa" },
            { label: "Africa/Algiers", value: "Africa/Algiers" },
            { label: "Africa/Asmara", value: "Africa/Asmara" },
            { label: "Africa/Bamako", value: "Africa/Bamako" },
            { label: "Africa/Bangui", value: "Africa/Bangui" },
            { label: "Africa/Banjul", value: "Africa/Banjul" },
            { label: "Africa/Bissau", value: "Africa/Bissau" },
            { label: "Africa/Blantyre", value: "Africa/Blantyre" },
            { label: "Africa/Brazzaville", value: "Africa/Brazzaville" },
            { label: "Africa/Bujumbura", value: "Africa/Bujumbura" },
            { label: "Africa/Cairo", value: "Africa/Cairo" },
            { label: "Africa/Casablanca", value: "Africa/Casablanca" },
            { label: "Africa/Ceuta", value: "Africa/Ceuta" },
            { label: "Africa/Conakry", value: "Africa/Conakry" },
            { label: "Africa/Dakar", value: "Africa/Dakar" },
            { label: "Africa/Dar_es_Salaam", value: "Africa/Dar_es_Salaam" },
            { label: "Africa/Djibouti", value: "Africa/Djibouti" },
            { label: "Africa/Douala", value: "Africa/Douala" },
            { label: "Africa/El_Aaiun", value: "Africa/El_Aaiun" },
            { label: "Africa/Freetown", value: "Africa/Freetown" },
            { label: "Africa/Gaborone", value: "Africa/Gaborone" },
            { label: "Africa/Harare", value: "Africa/Harare" },
            { label: "Africa/Johannesburg", value: "Africa/Johannesburg" },
            { label: "Africa/Juba", value: "Africa/Juba" },
            { label: "Africa/Kampala", value: "Africa/Kampala" },
            { label: "Africa/Khartoum", value: "Africa/Khartoum" },
            { label: "Africa/Kigali", value: "Africa/Kigali" },
            { label: "Africa/Kinshasa", value: "Africa/Kinshasa" },
            { label: "Africa/Lagos", value: "Africa/Lagos" },
            { label: "Africa/Libreville", value: "Africa/Libreville" },
            { label: "Africa/Lome", value: "Africa/Lome" },
            { label: "Africa/Luanda", value: "Africa/Luanda" },
            { label: "Africa/Lubumbashi", value: "Africa/Lubumbashi" },
            { label: "Africa/Lusaka", value: "Africa/Lusaka" },
            { label: "Africa/Malabo", value: "Africa/Malabo" },
            { label: "Africa/Maputo", value: "Africa/Maputo" },
            { label: "Africa/Maseru", value: "Africa/Maseru" },
            { label: "Africa/Mbabane", value: "Africa/Mbabane" },
            { label: "Africa/Mogadishu", value: "Africa/Mogadishu" },
            { label: "Africa/Monrovia", value: "Africa/Monrovia" },
            { label: "Africa/Nairobi", value: "Africa/Nairobi" },
            { label: "Africa/Ndjamena", value: "Africa/Ndjamena" },
            { label: "Africa/Niamey", value: "Africa/Niamey" },
            { label: "Africa/Nouakchott", value: "Africa/Nouakchott" },
            { label: "Africa/Ouagadougou", value: "Africa/Ouagadougou" },
            { label: "Africa/Porto-Novo", value: "Africa/Porto-Novo" },
            { label: "Africa/Sao_Tome", value: "Africa/Sao_Tome" },
            { label: "Africa/Tripoli", value: "Africa/Tripoli" },
            { label: "Africa/Tunis", value: "Africa/Tunis" },
            { label: "Africa/Windhoek", value: "Africa/Windhoek" },

            { label: "America/Adak", value: "America/Adak" },
            { label: "America/Anchorage", value: "America/Anchorage" },
            { label: "America/Anguilla", value: "America/Anguilla" },
            { label: "America/Antigua", value: "America/Antigua" },
            { label: "America/Araguaina", value: "America/Araguaina" },
            { label: "America/Argentina/Buenos_Aires", value: "America/Argentina/Buenos_Aires" },
            { label: "America/Argentina/Catamarca", value: "America/Argentina/Catamarca" },
            { label: "America/Argentina/Cordoba", value: "America/Argentina/Cordoba" },
            { label: "America/Argentina/Jujuy", value: "America/Argentina/Jujuy" },
            { label: "America/Argentina/La_Rioja", value: "America/Argentina/La_Rioja" },
            { label: "America/Argentina/Mendoza", value: "America/Argentina/Mendoza" },
            { label: "America/Argentina/Rio_Gallegos", value: "America/Argentina/Rio_Gallegos" },
            { label: "America/Argentina/Salta", value: "America/Argentina/Salta" },
            { label: "America/Argentina/San_Juan", value: "America/Argentina/San_Juan" },
            { label: "America/Argentina/San_Luis", value: "America/Argentina/San_Luis" },
            { label: "America/Argentina/Tucuman", value: "America/Argentina/Tucuman" },
            { label: "America/Argentina/Ushuaia", value: "America/Argentina/Ushuaia" },

            { label: "America/Chicago", value: "America/Chicago" },
            { label: "America/Denver", value: "America/Denver" },
            { label: "America/Detroit", value: "America/Detroit" },
            { label: "America/Los_Angeles", value: "America/Los_Angeles" },
            { label: "America/New_York", value: "America/New_York" },
            { label: "America/Phoenix", value: "America/Phoenix" },
            { label: "America/Toronto", value: "America/Toronto" },
            { label: "America/Vancouver", value: "America/Vancouver" },
            { label: "America/Winnipeg", value: "America/Winnipeg" },

            { label: "Antarctica/Casey", value: "Antarctica/Casey" },
            { label: "Antarctica/Davis", value: "Antarctica/Davis" },
            { label: "Antarctica/McMurdo", value: "Antarctica/McMurdo" },
            { label: "Antarctica/Palmer", value: "Antarctica/Palmer" },
            { label: "Antarctica/Troll", value: "Antarctica/Troll" },
            { label: "Antarctica/Vostok", value: "Antarctica/Vostok" },

            { label: "Arctic/Longyearbyen", value: "Arctic/Longyearbyen" },

            { label: "Asia/Aden", value: "Asia/Aden" },
            { label: "Asia/Almaty", value: "Asia/Almaty" },
            { label: "Asia/Amman", value: "Asia/Amman" },
            { label: "Asia/Baghdad", value: "Asia/Baghdad" },
            { label: "Asia/Baku", value: "Asia/Baku" },
            { label: "Asia/Bangkok", value: "Asia/Bangkok" },
            { label: "Asia/Beirut", value: "Asia/Beirut" },
            { label: "Asia/Dhaka", value: "Asia/Dhaka" },
            { label: "Asia/Dubai", value: "Asia/Dubai" },
            { label: "Asia/Gaza", value: "Asia/Gaza" },
            { label: "Asia/Hong_Kong", value: "Asia/Hong_Kong" },
            { label: "Asia/Jakarta", value: "Asia/Jakarta" },
            { label: "Asia/Jerusalem", value: "Asia/Jerusalem" },
            { label: "Asia/Kabul", value: "Asia/Kabul" },
            { label: "Asia/Karachi", value: "Asia/Karachi" },
            { label: "Asia/Kathmandu", value: "Asia/Kathmandu" },
            { label: "Asia/Kolkata", value: "Asia/Kolkata" },
            { label: "Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur" },
            { label: "Asia/Manila", value: "Asia/Manila" },
            { label: "Asia/Seoul", value: "Asia/Seoul" },
            { label: "Asia/Shanghai", value: "Asia/Shanghai" },
            { label: "Asia/Singapore", value: "Asia/Singapore" },
            { label: "Asia/Taipei", value: "Asia/Taipei" },
            { label: "Asia/Tehran", value: "Asia/Tehran" },
            { label: "Asia/Tokyo", value: "Asia/Tokyo" },
            { label: "Asia/Ulaanbaatar", value: "Asia/Ulaanbaatar" },
            { label: "Asia/Vladivostok", value: "Asia/Vladivostok" },
            { label: "Asia/Yangon", value: "Asia/Yangon" },
            { label: "Asia/Yekaterinburg", value: "Asia/Yekaterinburg" },

            { label: "Atlantic/Azores", value: "Atlantic/Azores" },
            { label: "Atlantic/Bermuda", value: "Atlantic/Bermuda" },
            { label: "Atlantic/Canary", value: "Atlantic/Canary" },
            { label: "Atlantic/Cape_Verde", value: "Atlantic/Cape_Verde" },
            { label: "Atlantic/Reykjavik", value: "Atlantic/Reykjavik" },

            { label: "Australia/Adelaide", value: "Australia/Adelaide" },
            { label: "Australia/Brisbane", value: "Australia/Brisbane" },
            { label: "Australia/Darwin", value: "Australia/Darwin" },
            { label: "Australia/Hobart", value: "Australia/Hobart" },
            { label: "Australia/Melbourne", value: "Australia/Melbourne" },
            { label: "Australia/Perth", value: "Australia/Perth" },
            { label: "Australia/Sydney", value: "Australia/Sydney" },

            { label: "Europe/Amsterdam", value: "Europe/Amsterdam" },
            { label: "Europe/Andorra", value: "Europe/Andorra" },
            { label: "Europe/Athens", value: "Europe/Athens" },
            { label: "Europe/Belgrade", value: "Europe/Belgrade" },
            { label: "Europe/Berlin", value: "Europe/Berlin" },
            { label: "Europe/Bratislava", value: "Europe/Bratislava" },
            { label: "Europe/Brussels", value: "Europe/Brussels" },
            { label: "Europe/Bucharest", value: "Europe/Bucharest" },
            { label: "Europe/Budapest", value: "Europe/Budapest" },
            { label: "Europe/Copenhagen", value: "Europe/Copenhagen" },
            { label: "Europe/Dublin", value: "Europe/Dublin" },
            { label: "Europe/Helsinki", value: "Europe/Helsinki" },
            { label: "Europe/Istanbul", value: "Europe/Istanbul" },
            { label: "Europe/Kyiv", value: "Europe/Kyiv" },
            { label: "Europe/Lisbon", value: "Europe/Lisbon" },
            { label: "Europe/Ljubljana", value: "Europe/Ljubljana" },
            { label: "Europe/London", value: "Europe/London" },
            { label: "Europe/Luxembourg", value: "Europe/Luxembourg" },
            { label: "Europe/Madrid", value: "Europe/Madrid" },
            { label: "Europe/Minsk", value: "Europe/Minsk" },
            { label: "Europe/Moscow", value: "Europe/Moscow" },
            { label: "Europe/Oslo", value: "Europe/Oslo" },
            { label: "Europe/Paris", value: "Europe/Paris" },
            { label: "Europe/Prague", value: "Europe/Prague" },
            { label: "Europe/Riga", value: "Europe/Riga" },
            { label: "Europe/Rome", value: "Europe/Rome" },
            { label: "Europe/Stockholm", value: "Europe/Stockholm" },
            { label: "Europe/Tallinn", value: "Europe/Tallinn" },
            { label: "Europe/Vienna", value: "Europe/Vienna" },
            { label: "Europe/Vilnius", value: "Europe/Vilnius" },
            { label: "Europe/Warsaw", value: "Europe/Warsaw" },
            { label: "Europe/Zurich", value: "Europe/Zurich" },

            { label: "Indian/Maldives", value: "Indian/Maldives" },
            { label: "Indian/Mauritius", value: "Indian/Mauritius" },
            { label: "Indian/Reunion", value: "Indian/Reunion" },

            { label: "Pacific/Auckland", value: "Pacific/Auckland" },
            { label: "Pacific/Fiji", value: "Pacific/Fiji" },
            { label: "Pacific/Guam", value: "Pacific/Guam" },
            { label: "Pacific/Honolulu", value: "Pacific/Honolulu" },
            { label: "Pacific/Tahiti", value: "Pacific/Tahiti" },

            { label: "UTC", value: "UTC" },
        ],
        icon: <Earth size={18} />,
        value: "Europe/Berlin",
        deviceInternal: true,
    },

    // Advanced settings
    {
        id: "PRIVACY_THRESHOLD",
        name: "Privacy Threshold",
        description: "Defines how strictly human content is filtered",
        defaultValue: 0,
        tab: "PRIVACY",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "0%", value: 0 },
            { label: "1%", value: 1 },
            { label: "2%", value: 2 },
            { label: "3%", value: 3 },
        ],
        icon: <HatGlasses size={18} />,
        value: 0,
        deviceInternal: true,
    },
    {
        id: "FULL_DISK",
        name: "Limit Storage Rules",
        description: "Delete old files or stop recording",
        defaultValue: "purge",
        tab: "DISK MANAGEMENT",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "Purge", value: "purge" },
            { label: "Keep", value: "keep" },
        ],
        icon: <DatabaseBackup size={18} />,
        value: "purge",
        deviceInternal: true,
    },
    {
        id: "PURGE_THRESHOLD",
        name: "Purge Threshold",
        description: "How full the storage must be to trigger purging of old files",
        defaultValue: 95,
        tab: "DISK MANAGEMENT",
        topTab: "ADVANCED",
        type: "number",
        icon: <ShieldAlert size={18} />,
        value: 95,
        deviceInternal: true,
    },
    {
        id: "MAX_FILES_SPECIES",
        name: "Max Files per Species",
        description: "0 = Keep all files, otherwise the maximum number of files to keep per species",
        defaultValue: 0,
        tab: "DISK MANAGEMENT",
        topTab: "ADVANCED",
        type: "number",
        icon: <Bird size={18} />,
        value: 0,
        deviceInternal: true,
    },
    {
        id: "REC_CARD",
        name: "Audio Card",
        description: "Use default for PulseAudio (recommended) or an ALSA device from arecord -L. Prefer dsnoop if available",
        defaultValue: "default",
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "string",
        icon: <Gpu size={18} />,
        value: "default",
        deviceInternal: true,
    },
    {
        id: "CHANNELS",
        name: "Audio Channels",
        description: "Set Channels to the number of channels supported by your sound card. 32 max",
        defaultValue: 2,
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Tv size={18} />,
        value: 2,
        deviceInternal: true,
        min: 1,
        max: 32,
    },
    {
        id: "RECORDING_LENGTH",
        name: "Recording Length",
        description: "Multiples of 3 are recommended",
        defaultValue: 15,
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Videotape size={18} />,
        value: 15,
        deviceInternal: true,
        min: 3,
        max: 60,
    },
    {
        id: "EXTRACTION_LENGTH",
        name: "Extraction Length",
        description: "Set Extraction Length to something less than your Recording Length",
        defaultValue: undefined,
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Videotape size={18} />,
        value: undefined,
        deviceInternal: true,
        min: 3,
    },
    {
        id: "AUDIOFMT",
        name: "Extractions Audio Format",
        description: "Defines the audio format for extractions",
        defaultValue: "mp3",
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "mp3", value: "mp3" },
            { label: "wav", value: "wav" },
            { label: "flac", value: "flac" },
            { label: "ogg", value: "ogg" },
            { label: "vorbis", value: "vorbis" },
            { label: "mp2", value: "mp2" },
            { label: "raw", value: "raw" },
            { label: "wavpcm", value: "wavpcm" },
            { label: "w64", value: "w64" },
            { label: "wv", value: "wv" },
            { label: "voc", value: "voc" },
            { label: "au", value: "au" },
            { label: "aiff", value: "aiff" },
            { label: "aif", value: "aif" },
            { label: "caf", value: "caf" },
            { label: "snd", value: "snd" },
            { label: "vox", value: "vox" },
            { label: "gsm", value: "gsm" },
            { label: "amr-nb", value: "amr-nb" },
            { label: "amr-wb", value: "amr-wb" },
        ],
        icon: <BookHeadphones size={18} />,
        value: "mp3",
        deviceInternal: true,
    },
    {
        id: "RTSP_STREAM",
        name: "RTSP Stream URL",
        description: "This will be used as audio source",
        defaultValue: "",
        tab: "AUDIO SETTINGS",
        topTab: "ADVANCED",
        type: "string",
        icon: <Link size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "AUTOMATIC_UPDATE",
        name: "Automatic Update",
        description: "Enables automatic update of the installation each Sunday at 3:00 AM",
        defaultValue: false,
        tab: "OPTIONS",
        topTab: "ADVANCED",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "RARE_SPECIES_THRESHOLD",
        name: "Rare Species Threshold (days)",
        description: "Defines after how many days since last detection a species is considered rare",
        defaultValue: 30,
        tab: "OPTIONS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Bird size={18} />,
        value: 30,
        deviceInternal: true,
    },
    {
        id: "OVERLAP",
        name: "Overlap (seconds)",
        description: "Defines the overlap duration for audio processing",
        defaultValue: 0.0,
        tab: "BIRDNET-LITE SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Blend size={18} />,
        value: 0.0,
        deviceInternal: true,
        min: 0.0,
        max: 2.9,
        step: 0.1,
    },
    {
        id: "CONFIDENCE",
        name: "Minimum Confidence",
        description: "Defines the minimum confidence level for detections",
        defaultValue: 0.7,
        tab: "BIRDNET-LITE SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Gauge size={18} />,
        value: 0.7,
        deviceInternal: true,
        min: 0.01,
        max: 0.99,
        step: 0.01,
    },
    {
        id: "SENSITIVITY",
        name: "Sigmoid Sensitivity",
        description: "Defines the sensitivity of the sigmoid function for detections",
        defaultValue: 1.25,
        tab: "BIRDNET-LITE SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Activity size={18} />,
        value: 1.25,
        deviceInternal: true,
        min: 0.5,
        max: 1.5,
        step: 0.01,
    },
    {
        id: "FREQSHIFT_TOOL",
        name: "Shifting tool",
        description: "Select the tool for shifting audio files",
        defaultValue: "sox",
        tab: "ACCESSIBILITY SETTINGS",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "sox", value: "sox" },
            { label: "ffmpeg", value: "ffmpeg" },
        ],
        icon: <Wrench size={18} />,
        value: "sox",
        deviceInternal: true,
    },
    {
        id: "FREQSHIFT_HI",
        name: "Frequency Shift Origin (Hz)",
        description: "Defines the origin frequency for the frequency shift",
        defaultValue: 6000,
        tab: "ACCESSIBILITY SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <AudioWaveform size={18} />,
        value: 6000,
        deviceInternal: true,
        min: 0,
        max: 20000,
        step: 1,
    },
    {
        id: "FREQSHIFT_LO",
        name: "Frequency Shift Target (Hz)",
        description: "Defines the target frequency for the frequency shift",
        defaultValue: 3000,
        tab: "ACCESSIBILITY SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <AudioWaveform size={18} />,
        value: 3000,
        deviceInternal: true,
        min: 0,
        max: 20000,
        step: 1,
    },
    {
        id: "FREQSHIFT_RECONNECT_DELAY",
        name: "Livestream reconnection delay (in ms)",
        description: "Defines the delay for reconnecting to the livestream",
        defaultValue: 4000,
        tab: "ACCESSIBILITY SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <WifiSync size={18} />,
        value: 4000,
        deviceInternal: true,
        min: 1000,
        max: 10000,
        step: 100,
    },
    {
        id: "FREQSHIFT_PITCH",
        name: "Pitch shift",
        description: "Defines the pitch shift for the audio",
        defaultValue: -1500,
        tab: "ACCESSIBILITY SETTINGS",
        topTab: "ADVANCED",
        type: "number",
        icon: <Diff size={18} />,
        value: -1500,
        deviceInternal: true,
        min: -4000,
        max: 4000,
        step: 1,
    },
    {
        id: "LogLevel_BirdnetRecordingService",
        name: "Birdnet Recording",
        description: "Select the logging level for the Birdnet Recording service",
        defaultValue: "error",
        tab: "LOGGING LEVELS",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "Errors Only", value: "error" },
            { label: "Warning", value: "warning" },
            { label: "Info", value: "info" },
            { label: "Debug", value: "debug" },
        ],
        icon: <ScrollText size={18} />,
        value: "error",
        deviceInternal: true,
    },
    {
        id: "LogLevel_LiveAudioStreamService",
        name: "Live Audio Stream",
        description: "Select the logging level for the Live Audio Stream service",
        defaultValue: "error",
        tab: "LOGGING LEVELS",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "Errors Only", value: "error" },
            { label: "Warning", value: "warning" },
            { label: "Info", value: "info" },
            { label: "Debug", value: "debug" },
        ],
        icon: <ScrollText size={18} />,
        value: "error",
        deviceInternal: true,
    },
    {
        id: "LogLevel_SpectrogramViewerService",
        name: "Spectrogram Service",
        description: "Select the logging level for the Spectrogram Viewer service",
        defaultValue: "error",
        tab: "LOGGING LEVELS",
        topTab: "ADVANCED",
        type: "select",
        selectOptions: [
            { label: "Errors Only", value: "error" },
            { label: "Warning", value: "warning" },
            { label: "Info", value: "info" },
            { label: "Debug", value: "debug" },
        ],
        icon: <ScrollText size={18} />,
        value: "error",
        deviceInternal: true,
    },
];
