import { Setting } from "../../lib/types";
import { Wifi, RefreshCw, KeyRound, Database, DatabaseZap } from "lucide-react";

export const DEFAULT_SETTINGS: Setting[] = [
    {
        id: "connection",
        name: "Connection",
        description: "Shows your device's connection name",
        defaultValue: "MyBirdNETPiHotspot",
        tab: "SYNCING",
        type: "string",
        icon: <Wifi size={18} />,
        disabled: true,
        value: "MyBirdNETPiHotspot",
    },
    {
        id: "deleteSyncedData",
        name: "Delete synced data",
        description: "Delete your data from the device after successful sync",
        defaultValue: false,
        tab: "SYNCING",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
    },
    {
        id: "mapTilerApiKey",
        name: "MapTiler API Key",
        description: "API key for MapTiler to unlock improved map features",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <KeyRound size={18} />,
        value: "",
    },
    {
        id: "supabaseUrl",
        name: "Supabase URL",
        description: "URL for your Supabase instance to enable cloud syncing",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <Database size={18} />,
        value: "",
    },
    {
        id: "supabaseKey",
        name: "Supabase Key",
        description: "Publishable key for your Supabase instance",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <DatabaseZap size={18} />,
        value: "",
    },
];
