import { Setting } from "../../lib/types";
import { Earth, Globe, CalendarClock, Bell, Router, Wifi, RefreshCw, KeyRound, Database, DatabaseZap, Package, Tag, AudioWaveform, ALargeSmall, MapPin } from "lucide-react";

export const DEFAULT_SETTINGS: Setting[] = [
    {
        id: "connection",
        name: "Connection",
        description: "Shows your device's connection name",
        defaultValue: "MyBirdNETPiHotspot",
        tab: "SYNCING",
        type: "string",
        icon: <Wifi size={18} />,
        disabled: true,
        value: "MyBirdNETPiHotspot",
    },
    {
        id: "deleteSyncedData",
        name: "Delete synced data",
        description: "Delete your data from the device after successful sync",
        defaultValue: false,
        tab: "SYNCING",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: false,
    },
    {
        id: "mapTilerApiKey",
        name: "MapTiler API Key",
        description: "API key for MapTiler to unlock improved map features",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <KeyRound size={18} />,
        value: "",
    },
    {
        id: "supabaseUrl",
        name: "Supabase URL",
        description: "URL for your Supabase instance to enable cloud syncing",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <Database size={18} />,
        value: "",
    },
    {
        id: "supabaseKey",
        name: "Supabase Key",
        description: "Publishable key for your Supabase instance",
        defaultValue: "",
        tab: "CREDENTIALS",
        type: "string",
        icon: <DatabaseZap size={18} />,
        value: "",
    },
    // TODO icons anpassen

    // Device internal settings
    // Basic settings
    {
        id: "model",
        name: "Model",
        description: "Type of model used for predictions",
        defaultValue: "BirdNET_GLOBAL_6K_V2.4_Model_FP16",
        tab: "MODEL",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "BirdNET_GLOBAL_6K_V2.4_Model_FP16", value: "BirdNET_GLOBAL_6K_V2.4_Model_FP16" },
            { label: "BirdNET_6K_GLOBAL_MODEL", value: "BirdNET_6K_GLOBAL_MODEL" },
        ],
        icon: <Package size={18} />,
        value: "BirdNET_GLOBAL_6K_V2.4_Model_FP16",
        deviceInternal: true,
    },
    {
        id: "data_model_version",
        name: "Species range model V2.4 - V2",
        description: "Version of the species range model used for predictions",
        defaultValue: false,
        tab: "MODEL",
        topTab: "BASIC",
        type: "boolean",
        icon: <Tag size={18} />,
        value: false,
        deviceInternal: true,
    },
    {
        id: "sf_thresh",
        name: "Species Occurrence Frequency Threshold",
        description: "Minimum occurrence frequency for a species to be included in the model's output",
        defaultValue: 0.03,
        tab: "MODEL",
        topTab: "BASIC",
        type: "number",
        icon: <AudioWaveform size={18} />,
        value: 0.03,
        min: 0.0005,
        max: 0.99,
        deviceInternal: true,
    },
    {
        id: "site_name",
        name: "Site Name",
        description: "The name of your device",
        defaultValue: "birdnet",
        tab: "LOCATION",
        topTab: "BASIC",
        type: "string",
        icon: <ALargeSmall size={18} />,
        value: "birdnet",
        deviceInternal: true,
    },
    {
        id: "latitude",
        name: "Latitude",
        description: "Latitude of the device location",
        defaultValue: 49.0181,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "number",
        icon: <MapPin size={18} />,
        value: 49.0181,
        min: -90.0,
        max: 90.0,
        step: 0.0001,
        deviceInternal: true,
        disabled: true
    },
    {
        id: "longitude",
        name: "Longitude",
        description: "Longitude of the device location",
        defaultValue: 12.1404,
        tab: "LOCATION",
        topTab: "BASIC",
        type: "number",
        icon: <MapPin size={18} />,
        value: 12.1404,
        min: -180.0,
        max: 180.0,
        step: 0.0001,
        deviceInternal: true,
        disabled: true
    },
    {
        id: "birdweather_id",
        name: "BirdWeather Token",
        description: "Used for sharing your data with the BirdWeather community platform",
        defaultValue: "",
        tab: "BIRDWEATHER",
        topTab: "BASIC",
        type: "string",
        icon: <Router size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "apprise_input",
        name: "Apprise Notifications Configuration",
        description: "More here: <a href='https://github.com/caronc/apprise/wiki'>Apprise Documentation</a>",
        defaultValue: "",
        tab: "NOTIFICATIONS",
        topTab: "BASIC",
        type: "textarea",
        icon: <Bell size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "language",
        name: "Database Language",
        description: "! Only modify this at initial setup !",
        defaultValue: "en",
        tab: "LOCALIZATION",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "Afrikaans", value: "af" },
            { label: "Arabic", value: "ar" },
            { label: "Catalan", value: "ca" },
            { label: "Czech", value: "cs" },
            { label: "Chinese (simplified)", value: "zh_CN" },
            { label: "Chinese (traditional)", value: "zh_TW" },
            { label: "Croatian", value: "hr" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Indonesia", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuania", value: "lt" },
            { label: "Norwegian", value: "no" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Serbian", value: "sr" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Thai", value: "th" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" },
            { label: "Vietnamese", value: "vi" },
        ],
        icon: <Globe size={18} />,
        value: "en",
        deviceInternal: true,
    },
    {
        id: "retrieveTimeAutomatically",
        name: "Retrieve Time",
        description: "Automatically retrieve the current time from the network",
        defaultValue: true,
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "boolean",
        icon: <RefreshCw size={18} />,
        value: true,
        deviceInternal: true,
    },
    {
        id: "date",
        name: "Date",
        description: "Shows the current date for the device",
        defaultValue: "",
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "string",
        icon: <CalendarClock size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "time",
        name: "Time",
        description: "Shows the current time for the device",
        defaultValue: "",
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "string",
        icon: <CalendarClock size={18} />,
        value: "",
        deviceInternal: true,
    },
    {
        id: "timezone",
        name: "Select a Timezone",
        description: "Select the timezone for your device to ensure correct timestamping of detections",
        defaultValue: "Europe/Berlin",
        tab: "TIME AND DATE",
        topTab: "BASIC",
        type: "select",
        selectOptions: [
            { label: "Africa/Abidjan", value: "Africa/Abidjan" },
            { label: "Africa/Accra", value: "Africa/Accra" },
            { label: "Africa/Addis_Ababa", value: "Africa/Addis_Ababa" },
            { label: "Africa/Algiers", value: "Africa/Algiers" },
            { label: "Africa/Asmara", value: "Africa/Asmara" },
            { label: "Africa/Bamako", value: "Africa/Bamako" },
            { label: "Africa/Bangui", value: "Africa/Bangui" },
            { label: "Africa/Banjul", value: "Africa/Banjul" },
            { label: "Africa/Bissau", value: "Africa/Bissau" },
            { label: "Africa/Blantyre", value: "Africa/Blantyre" },
            { label: "Africa/Brazzaville", value: "Africa/Brazzaville" },
            { label: "Africa/Bujumbura", value: "Africa/Bujumbura" },
            { label: "Africa/Cairo", value: "Africa/Cairo" },
            { label: "Africa/Casablanca", value: "Africa/Casablanca" },
            { label: "Africa/Ceuta", value: "Africa/Ceuta" },
            { label: "Africa/Conakry", value: "Africa/Conakry" },
            { label: "Africa/Dakar", value: "Africa/Dakar" },
            { label: "Africa/Dar_es_Salaam", value: "Africa/Dar_es_Salaam" },
            { label: "Africa/Djibouti", value: "Africa/Djibouti" },
            { label: "Africa/Douala", value: "Africa/Douala" },
            { label: "Africa/El_Aaiun", value: "Africa/El_Aaiun" },
            { label: "Africa/Freetown", value: "Africa/Freetown" },
            { label: "Africa/Gaborone", value: "Africa/Gaborone" },
            { label: "Africa/Harare", value: "Africa/Harare" },
            { label: "Africa/Johannesburg", value: "Africa/Johannesburg" },
            { label: "Africa/Juba", value: "Africa/Juba" },
            { label: "Africa/Kampala", value: "Africa/Kampala" },
            { label: "Africa/Khartoum", value: "Africa/Khartoum" },
            { label: "Africa/Kigali", value: "Africa/Kigali" },
            { label: "Africa/Kinshasa", value: "Africa/Kinshasa" },
            { label: "Africa/Lagos", value: "Africa/Lagos" },
            { label: "Africa/Libreville", value: "Africa/Libreville" },
            { label: "Africa/Lome", value: "Africa/Lome" },
            { label: "Africa/Luanda", value: "Africa/Luanda" },
            { label: "Africa/Lubumbashi", value: "Africa/Lubumbashi" },
            { label: "Africa/Lusaka", value: "Africa/Lusaka" },
            { label: "Africa/Malabo", value: "Africa/Malabo" },
            { label: "Africa/Maputo", value: "Africa/Maputo" },
            { label: "Africa/Maseru", value: "Africa/Maseru" },
            { label: "Africa/Mbabane", value: "Africa/Mbabane" },
            { label: "Africa/Mogadishu", value: "Africa/Mogadishu" },
            { label: "Africa/Monrovia", value: "Africa/Monrovia" },
            { label: "Africa/Nairobi", value: "Africa/Nairobi" },
            { label: "Africa/Ndjamena", value: "Africa/Ndjamena" },
            { label: "Africa/Niamey", value: "Africa/Niamey" },
            { label: "Africa/Nouakchott", value: "Africa/Nouakchott" },
            { label: "Africa/Ouagadougou", value: "Africa/Ouagadougou" },
            { label: "Africa/Porto-Novo", value: "Africa/Porto-Novo" },
            { label: "Africa/Sao_Tome", value: "Africa/Sao_Tome" },
            { label: "Africa/Tripoli", value: "Africa/Tripoli" },
            { label: "Africa/Tunis", value: "Africa/Tunis" },
            { label: "Africa/Windhoek", value: "Africa/Windhoek" },

            { label: "America/Adak", value: "America/Adak" },
            { label: "America/Anchorage", value: "America/Anchorage" },
            { label: "America/Anguilla", value: "America/Anguilla" },
            { label: "America/Antigua", value: "America/Antigua" },
            { label: "America/Araguaina", value: "America/Araguaina" },
            { label: "America/Argentina/Buenos_Aires", value: "America/Argentina/Buenos_Aires" },
            { label: "America/Argentina/Catamarca", value: "America/Argentina/Catamarca" },
            { label: "America/Argentina/Cordoba", value: "America/Argentina/Cordoba" },
            { label: "America/Argentina/Jujuy", value: "America/Argentina/Jujuy" },
            { label: "America/Argentina/La_Rioja", value: "America/Argentina/La_Rioja" },
            { label: "America/Argentina/Mendoza", value: "America/Argentina/Mendoza" },
            { label: "America/Argentina/Rio_Gallegos", value: "America/Argentina/Rio_Gallegos" },
            { label: "America/Argentina/Salta", value: "America/Argentina/Salta" },
            { label: "America/Argentina/San_Juan", value: "America/Argentina/San_Juan" },
            { label: "America/Argentina/San_Luis", value: "America/Argentina/San_Luis" },
            { label: "America/Argentina/Tucuman", value: "America/Argentina/Tucuman" },
            { label: "America/Argentina/Ushuaia", value: "America/Argentina/Ushuaia" },

            { label: "America/Chicago", value: "America/Chicago" },
            { label: "America/Denver", value: "America/Denver" },
            { label: "America/Detroit", value: "America/Detroit" },
            { label: "America/Los_Angeles", value: "America/Los_Angeles" },
            { label: "America/New_York", value: "America/New_York" },
            { label: "America/Phoenix", value: "America/Phoenix" },
            { label: "America/Toronto", value: "America/Toronto" },
            { label: "America/Vancouver", value: "America/Vancouver" },
            { label: "America/Winnipeg", value: "America/Winnipeg" },

            { label: "Antarctica/Casey", value: "Antarctica/Casey" },
            { label: "Antarctica/Davis", value: "Antarctica/Davis" },
            { label: "Antarctica/McMurdo", value: "Antarctica/McMurdo" },
            { label: "Antarctica/Palmer", value: "Antarctica/Palmer" },
            { label: "Antarctica/Troll", value: "Antarctica/Troll" },
            { label: "Antarctica/Vostok", value: "Antarctica/Vostok" },

            { label: "Arctic/Longyearbyen", value: "Arctic/Longyearbyen" },

            { label: "Asia/Aden", value: "Asia/Aden" },
            { label: "Asia/Almaty", value: "Asia/Almaty" },
            { label: "Asia/Amman", value: "Asia/Amman" },
            { label: "Asia/Baghdad", value: "Asia/Baghdad" },
            { label: "Asia/Baku", value: "Asia/Baku" },
            { label: "Asia/Bangkok", value: "Asia/Bangkok" },
            { label: "Asia/Beirut", value: "Asia/Beirut" },
            { label: "Asia/Dhaka", value: "Asia/Dhaka" },
            { label: "Asia/Dubai", value: "Asia/Dubai" },
            { label: "Asia/Gaza", value: "Asia/Gaza" },
            { label: "Asia/Hong_Kong", value: "Asia/Hong_Kong" },
            { label: "Asia/Jakarta", value: "Asia/Jakarta" },
            { label: "Asia/Jerusalem", value: "Asia/Jerusalem" },
            { label: "Asia/Kabul", value: "Asia/Kabul" },
            { label: "Asia/Karachi", value: "Asia/Karachi" },
            { label: "Asia/Kathmandu", value: "Asia/Kathmandu" },
            { label: "Asia/Kolkata", value: "Asia/Kolkata" },
            { label: "Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur" },
            { label: "Asia/Manila", value: "Asia/Manila" },
            { label: "Asia/Seoul", value: "Asia/Seoul" },
            { label: "Asia/Shanghai", value: "Asia/Shanghai" },
            { label: "Asia/Singapore", value: "Asia/Singapore" },
            { label: "Asia/Taipei", value: "Asia/Taipei" },
            { label: "Asia/Tehran", value: "Asia/Tehran" },
            { label: "Asia/Tokyo", value: "Asia/Tokyo" },
            { label: "Asia/Ulaanbaatar", value: "Asia/Ulaanbaatar" },
            { label: "Asia/Vladivostok", value: "Asia/Vladivostok" },
            { label: "Asia/Yangon", value: "Asia/Yangon" },
            { label: "Asia/Yekaterinburg", value: "Asia/Yekaterinburg" },

            { label: "Atlantic/Azores", value: "Atlantic/Azores" },
            { label: "Atlantic/Bermuda", value: "Atlantic/Bermuda" },
            { label: "Atlantic/Canary", value: "Atlantic/Canary" },
            { label: "Atlantic/Cape_Verde", value: "Atlantic/Cape_Verde" },
            { label: "Atlantic/Reykjavik", value: "Atlantic/Reykjavik" },

            { label: "Australia/Adelaide", value: "Australia/Adelaide" },
            { label: "Australia/Brisbane", value: "Australia/Brisbane" },
            { label: "Australia/Darwin", value: "Australia/Darwin" },
            { label: "Australia/Hobart", value: "Australia/Hobart" },
            { label: "Australia/Melbourne", value: "Australia/Melbourne" },
            { label: "Australia/Perth", value: "Australia/Perth" },
            { label: "Australia/Sydney", value: "Australia/Sydney" },

            { label: "Europe/Amsterdam", value: "Europe/Amsterdam" },
            { label: "Europe/Andorra", value: "Europe/Andorra" },
            { label: "Europe/Athens", value: "Europe/Athens" },
            { label: "Europe/Belgrade", value: "Europe/Belgrade" },
            { label: "Europe/Berlin", value: "Europe/Berlin" },
            { label: "Europe/Bratislava", value: "Europe/Bratislava" },
            { label: "Europe/Brussels", value: "Europe/Brussels" },
            { label: "Europe/Bucharest", value: "Europe/Bucharest" },
            { label: "Europe/Budapest", value: "Europe/Budapest" },
            { label: "Europe/Copenhagen", value: "Europe/Copenhagen" },
            { label: "Europe/Dublin", value: "Europe/Dublin" },
            { label: "Europe/Helsinki", value: "Europe/Helsinki" },
            { label: "Europe/Istanbul", value: "Europe/Istanbul" },
            { label: "Europe/Kyiv", value: "Europe/Kyiv" },
            { label: "Europe/Lisbon", value: "Europe/Lisbon" },
            { label: "Europe/Ljubljana", value: "Europe/Ljubljana" },
            { label: "Europe/London", value: "Europe/London" },
            { label: "Europe/Luxembourg", value: "Europe/Luxembourg" },
            { label: "Europe/Madrid", value: "Europe/Madrid" },
            { label: "Europe/Minsk", value: "Europe/Minsk" },
            { label: "Europe/Moscow", value: "Europe/Moscow" },
            { label: "Europe/Oslo", value: "Europe/Oslo" },
            { label: "Europe/Paris", value: "Europe/Paris" },
            { label: "Europe/Prague", value: "Europe/Prague" },
            { label: "Europe/Riga", value: "Europe/Riga" },
            { label: "Europe/Rome", value: "Europe/Rome" },
            { label: "Europe/Stockholm", value: "Europe/Stockholm" },
            { label: "Europe/Tallinn", value: "Europe/Tallinn" },
            { label: "Europe/Vienna", value: "Europe/Vienna" },
            { label: "Europe/Vilnius", value: "Europe/Vilnius" },
            { label: "Europe/Warsaw", value: "Europe/Warsaw" },
            { label: "Europe/Zurich", value: "Europe/Zurich" },

            { label: "Indian/Maldives", value: "Indian/Maldives" },
            { label: "Indian/Mauritius", value: "Indian/Mauritius" },
            { label: "Indian/Reunion", value: "Indian/Reunion" },

            { label: "Pacific/Auckland", value: "Pacific/Auckland" },
            { label: "Pacific/Fiji", value: "Pacific/Fiji" },
            { label: "Pacific/Guam", value: "Pacific/Guam" },
            { label: "Pacific/Honolulu", value: "Pacific/Honolulu" },
            { label: "Pacific/Tahiti", value: "Pacific/Tahiti" },

            { label: "UTC", value: "UTC" },
        ],
        icon: <Earth size={18} />,
        value: "Europe/Berlin",
        deviceInternal: true,
    },
];
